make status_justify configurable
catppuccin/tmux pull request #145
Opened 2024-02-28 15:25 UTC by anopheles

2024-02-28 16:55 UTC, vdbe commented
The default for `status-justify` is left, would it not be better to just remove the set line for it and let users set it?
You can also just overwrite it.

2024-02-28 18:02 UTC, anopheles commented
I would only do that if I were confident that this theme works well with every justify setting. Otherwise an existing tmux config may look broken. Making this setting explicit moves the responsibility to the user. Otherwise, totally agree! 👍

2024-03-06 21:19 UTC, sgoudham requested changes
Hi :wave: 

Thanks for the PR, I think it has merit. 

I believe @89iuv would also want you to update the documentation to explicitly mention this option in the [README#Status](https://github.com/catppuccin/tmux?tab=readme-ov-file#status)

2024-03-15 16:06 UTC, anopheles commented on catppuccin.tmux
> +  local status_justify=$(get_tmux_option "@catppuccin_status_justify" "left")
done

2024-03-15 16:34 UTC, vdbe commented on catppuccin.tmux
> +  local status_justify=$(get_tmux_option "@catppuccin_status_justify" "left")
```bash
  # status
  local status_default=$(get_tmux_option "@catppuccin_status_default" "on")
  local status_justify=$(get_tmux_option "@catppuccin_status_justify" "left")

  set status "$status_default"
  set status-justify "$status_justify"
  set status-bg "${thm_bg}"
  set status-left-length "100"
  set status-right-length "100"
```

2024-03-17 15:11 UTC, sgoudham approved these changes

2024-03-17 15:43 UTC, vdbe approved these changes

2024-03-17 15:43 UTC, merged

2025-01-04 01:30 UTC, Danisaski commented
Why was this feature reverted?

2025-01-04 05:21 UTC, kjnsn commented
> Why was this feature reverted?

It's a tmux option. There's no value in configuring through catppuccin, just set the option to whatever you'd like

2025-01-04 10:24 UTC, Danisaski commented
> > Why was this feature reverted?
> 
> It's a tmux option. There's no value in configuring through catppuccin, just set the option to whatever you'd like

Thanks for the quick reply!