Add space to default window status icons
catppuccin/tmux pull request #156
Opened 2024-03-08 05:43 UTC by xwjdsh

Sometimes the window status icons get crowded,
<img width="527" alt="image" src="https://github.com/catppuccin/tmux/assets/11025519/80380a0a-d68a-4e12-957b-9bc22acbef83">

After the change,
<img width="537" alt="image" src="https://github.com/catppuccin/tmux/assets/11025519/1dfe4001-ad8a-49fb-b017-74b61167c99e">

2024-03-10 08:16 UTC, vdbe commented
The spacing is indeed needed, since we are changing the default icons here which of these 3 do you find better (or a combination)?
![image](https://github.com/catppuccin/tmux/assets/44153531/f048c3e2-d235-47cc-a43b-4e04dd256fbc)

```tmux
# Session 1 (suggested above)
set -g @catppuccin_icon_window_last "󰖰 "
set -g @catppuccin_icon_window_current "󰖯 "
set -g @catppuccin_icon_window_zoom "󰁌 "
set -g @catppuccin_icon_window_mark "󰃀 "
set -g @catppuccin_icon_window_silent "󰂛 "
set -g @catppuccin_icon_window_activity "󰖲 "
set -g @catppuccin_icon_window_bell "󰂞 "
```

```tmux
# Session 2
set -g @catppuccin_icon_window_last " "
set -g @catppuccin_icon_window_current " "
set -g @catppuccin_icon_window_zoom " "
set -g @catppuccin_icon_window_mark "󰃀 "
set -g @catppuccin_icon_window_silent "󰂠 "
set -g @catppuccin_icon_window_activity "󱅫 "
set -g @catppuccin_icon_window_bell "󰂞 "
```

```tmux
# Session 3
set -g @catppuccin_icon_window_last " "
set -g @catppuccin_icon_window_current " "
set -g @catppuccin_icon_window_zoom " "
set -g @catppuccin_icon_window_mark " "
set -g @catppuccin_icon_window_silent "󰂠 "
set -g @catppuccin_icon_window_activity "󱅫 "
set -g @catppuccin_icon_window_bell "󰂞 "
```

2024-03-10 17:21 UTC, xwjdsh commented
I personally prefer `Session 1`, they are all about the same size and look more coordinated, but the `window_activity_icon` I like "󱅫 ".
```
set -g @catppuccin_icon_window_last "󰖰 "
set -g @catppuccin_icon_window_current "󰖯 "
set -g @catppuccin_icon_window_zoom "󰁌 "
set -g @catppuccin_icon_window_mark "󰃀 "
set -g @catppuccin_icon_window_silent "󰂛 "
set -g @catppuccin_icon_window_activity "󱅫 "
set -g @catppuccin_icon_window_bell "󰂞 "
```

2024-03-11 15:03 UTC, vdbe requested changes

2024-03-11 15:03 UTC, vdbe commented on catppuccin.tmux
> +
Remove extra space

2024-03-11 15:03 UTC, vdbe commented on catppuccin.tmux
> +  local custom_icon_window_activity=$(get_tmux_option "@catppuccin_icon_window_activity" "󰖲 ")
Update icon to `󱅫`

2024-03-12 17:31 UTC, vdbe approved these changes

2024-03-12 17:32 UTC, merged