Add tmux-clima as another module for weather
catppuccin/tmux pull request #161
Opened 2024-03-15 02:07 UTC by xafarr

#160

2024-03-16 15:35 UTC, vdbe commented
What does this plugin provide that the the current weather module doesn't?
It seems to also use OpenWeatherMap so the result are the same I guess (and you need your own api key).

Before merging this it needs documentation in the README.

2024-03-17 01:09 UTC, xafarr commented
It does the same thing but in a different way. Also, [tmux-weather](https://github.com/xamut/tmux-weather) is pretty inactive. And [tmux-clima](https://github.com/vascomfnunes/tmux-clima) can be an extra option for people to use with **catppuccin/tmux**. Updated the PR with README update. Thanks.

2024-03-17 10:23 UTC, vdbe requested changes

2024-03-17 10:23 UTC, vdbe commented on README.md
> +### Weather modules
Link under `## Content` needs to be updated

2024-03-17 10:23 UTC, vdbe commented on README.md
> +#### [tmux-weather](https://github.com/xamut/tmux-weather)
```suggestion
#### tmux-weather
```
Already linked 3 lines below

2024-03-17 10:23 UTC, vdbe commented on README.md
> +#### [tmux-clima](https://github.com/vascomfnunes/tmux-clima)
```suggestion
#### https://github.com/vascomfnunes/tmux-clima
```

2024-03-17 10:23 UTC, vdbe commented
It currently does not do anything extra except set prefix+W.
I will leave this open in case this changes and for further discussion/requests.

2024-03-18 03:12 UTC, xafarr commented
I have been using **tmux-clima** for almost 2 years and contribute to it as well. I also like **catppuccin** project and use it in all terminal programs. I raised this PR for people like me to have an option to use these together. I used to use **tmux-weather** but was constantly having problems with *wttr.in*. That was the reason I moved to this plugin. *OpenWeatherMap API* is pretty stable and gives free 1000 calls per day.

2024-03-18 13:15 UTC, vdbe approved these changes

2024-03-18 13:16 UTC, merged