Clarify creating a custom module
catppuccin/tmux pull request #164
Opened 2024-03-16 21:59 UTC by qadzek

As requested by @sgoudham in #90

2024-03-16 23:29 UTC, sgoudham requested changes

2024-03-16 23:29 UTC, sgoudham commented on README.md
> +Look into [custom/README.md](https://github.com/catppuccin/tmux/blob/main/README.md) for more details.
```suggestion
For further details, see the documentation in [custom/README.md](custom/README.md)
```

2024-03-16 23:29 UTC, sgoudham commented on custom/README.md
I think it would be better to format this document as a series of numbered bullet points. Maybe something like the following?

```md
## Creating A New Module

> [!NOTE]
> Changes will only be applied after reloading your Tmux configuration by executing `tmux source-file ~/.tmux.conf`.

You can create a custom module by following the steps outlined below:

1. Create a new file in `~/.tmux/plugins/tmux/custom/<module_name>.sh` to store the custom module.
	- The file **must** end in `.sh`
	- The file **does not** need to be set as executable.
2. Copy the following template to this new file. Make sure to replace every instance of <module_name> by the name you chose as filename.

	```bash
	show_<module_name>() { # This function name must match the module name!
  		local index icon color text module

  		index=$1 # This variable is used internally by the module loader in order to know the position of this module 
  		icon="$(  get_tmux_option "@catppuccin_<module_name>_icon"  ""           )"
  		color="$( get_tmux_option "@catppuccin_<module_name>_color" "$thm_orange" )"
  		text="$(  get_tmux_option "@catppuccin_<module_name>_text"  "hello world" )"

  		module=$( build_status_module "$index" "$icon" "$color" "$text" )

  			echo "$module"
	}
	```

3. Add the custom module to the list of modules in `.tmux.conf`

	```bash
	set -g @catppuccin_status_modules_right "... <module_name> ..."
	```

## Customisation

...
```

What do you think?

2024-03-17 09:50 UTC, vdbe commented
I quite like the idea of mentioning required plugins for the module at the top like in [uptime](https://github.com/catppuccin/tmux/blob/4eb10fa510548891ac9c5afc5b43679096361fe3/status/weather.sh#L1).
Could this get a place in the template and be mentioned?

2024-03-17 15:21 UTC, sgoudham commented on custom/README.md
Just made some small tweaks regarding indentation, thanks!

2024-03-17 15:22 UTC, sgoudham approved these changes
Thanks for the PR!
Will leave this for @vdbe to merge.

2024-03-17 15:41 UTC, merged