Respect `status_background` in `message-style`
catppuccin/tmux pull request #193
Opened 2024-04-17 17:10 UTC by lluchkaa

When using `default` for `@catppuccin_status_background`, it still keeps background color for `message-style`. You can see it when you type a command in `tmux`.

Current implementation (with `@catppuccin_status_background` `"default"`):

<img width="519" alt="Screenshot 2024-04-17 at 20 06 38" src="https://github.com/catppuccin/tmux/assets/37471864/c8966499-4193-405a-a701-cea9d467ab01">

<img width="519" alt="Screenshot 2024-04-17 at 20 06 58" src="https://github.com/catppuccin/tmux/assets/37471864/c39247f0-e714-4920-b188-9ab448a1f785">

Respecting `@catppuccin_status_background` (with `@catppuccin_status_background` `"default"`):

<img width="519" alt="Screenshot 2024-04-17 at 20 07 53" src="https://github.com/catppuccin/tmux/assets/37471864/2c584528-e288-4f72-b8da-01fde24638d1">

<img width="519" alt="Screenshot 2024-04-17 at 20 08 44" src="https://github.com/catppuccin/tmux/assets/37471864/af022595-b4ae-4ed8-91a2-ad302c18a22f">

2024-04-17 17:12 UTC, lluchkaa commented on catppuccin.tmux
I replicated same structure of conditions as in `status_background` block above. I wanted to keep logic related to `messages` in separate place.

If you want to move `message_background` variable to existing if blocks above, let me know!

2024-04-18 16:43 UTC, vdbe requested changes

2024-04-18 16:43 UTC, vdbe commented on catppuccin.tmux
I would move message_background in the existing if block

2024-04-19 10:09 UTC, lluchkaa commented
@vdbe done!

2024-04-19 18:53 UTC, lluchkaa commented
> @vdbe done!

@vdbe could you, please, approve this PR

2024-04-20 08:43 UTC, vdbe approved these changes

2024-04-20 08:43 UTC, merged