Add cpu_mem & network module
catppuccin/tmux pull request #194
Opened 2024-04-20 06:05 UTC by lixin-wei

Add 2 handy modules: `cpu_mem` and `network`

<img width="894" alt="image" src="https://github.com/catppuccin/tmux/assets/19600697/f15d6d3f-ac0b-47fb-84f5-9257027023b9">

2024-04-29 19:23 UTC, vdbe requested changes

2024-04-29 19:23 UTC, vdbe commented on README.md
> +The preferred way to install tmux-cpu is using [TPM](https://github.com/tmux-plugins/tpm).
Clarify that this will build additional software

2024-04-29 19:23 UTC, vdbe commented on status/cpu_mem.sh
> +  text="$(get_tmux_option "@catppuccin_cpu_mem__text" "#($TMUX_PLUGIN_MANAGER_PATH/tmux-mem-cpu-load/tmux-mem-cpu-load --cpu-mode 2 --averages-count 0 --interval 2)")"
Add an extra option "@catppuccin_cpu_mem_args/options" with as default "--cpu-mode 2 --averages-count 0 --interval 2"

2024-04-29 19:23 UTC, vdbe commented on status/cpu_mem.sh
> +  text="$(get_tmux_option "@catppuccin_cpu_mem__text" "#($TMUX_PLUGIN_MANAGER_PATH/tmux-mem-cpu-load/tmux-mem-cpu-load --cpu-mode 2 --averages-count 0 --interval 2)")"
```suggestion
  text="$(get_tmux_option "@catppuccin_cpu_mem_text" "#($TMUX_PLUGIN_MANAGER_PATH/tmux-mem-cpu-load/tmux-mem-cpu-load --cpu-mode 2 --averages-count 0 --interval 2)")"
```
2 underscores between mem and text

2024-07-12 04:12 UTC, gambhirsharma commented
Hey, @lixin-wei, I'm having issues with the network module. It works when I install the plugin using `<prefix>+I`, but it keeps terminating after a while. Here’s what it looks like.

How can I fix it? 

https://github.com/user-attachments/assets/5d3c3fc9-b342-49be-8d85-41c3a6302ea4

2024-07-12 08:44 UTC, vdbe commented
@gambhirsharma is `set -g @plugin 'catppuccin/tmux'` placed before other plugins?

2024-07-12 14:47 UTC, gambhirsharma commented
> @gambhirsharma is `set -g @plugin 'catppuccin/tmux'` placed before other plugins?

Now it's showing the module but it doesn't render the internet speed text. Do I need to do something else to fix this? 
<img width="300" alt="image" src="https://github.com/user-attachments/assets/67c3ccd6-12b1-4ed2-9047-93c1965c11fa">

This is what my `.tmux.conf` look like: [Gist link](https://gist.github.com/gambhirsharma/862c65c3d5711cdfadcedfbeb69135c3)

2025-04-08 11:29 UTC, closed without merging