Don't add icon separator if there is no icon for a status module
catppuccin/tmux pull request #265
Opened 2024-08-03 23:59 UTC by j-xella

When rendering status modules, there is a separator between the icon and the module text. Before, it was redundantly shown even when the module icon was disabled by the user.

2024-08-04 08:14 UTC, vdbe requested changes
A better way to do this is before the echo check if an icons is empty and clear `$show_icon` if so

```bash
if [ -z "$icon] ; then
  show_icon=""
fi
```

2024-08-04 21:25 UTC, j-xella commented
Reimplemented, please have a look

2024-08-06 14:19 UTC, j-xella commented
It could possibly fix #85

2024-08-09 19:01 UTC, vdbe approved these changes

2024-08-09 19:20 UTC, merged